export const questions=[
 ['Introduction','자기소개를 해 보세요.','Please introduce yourself.','Ipakilala ang iyong sarili.','안녕하세요. 저는 [이름]입니다. 필리핀에서 왔습니다. 제조업에서 성실하게 일하고 싶습니다. 감사합니다.','Hello. I am [name], from the Philippines. I would like to work diligently in manufacturing. Thank you.','Magandang araw. Ako si [pangalan], mula sa Pilipinas. Nais kong magtrabaho nang masipag sa manufacturing. Salamat.'],
 ['Introduction','왜 한국에서 일하고 싶습니까?','Why do you want to work in Korea?','Bakit mo gustong magtrabaho sa Korea?','한국에서 제조업 기술을 배우고 가족을 돕고 싶습니다.','I want to learn manufacturing skills in Korea and support my family.','Gusto kong matuto ng mga kasanayan sa manufacturing sa Korea at makatulong sa pamilya ko.'],
 ['Experience','공장에서 일한 경험이 있습니까?','Have you worked in a factory?','May karanasan ka bang magtrabaho sa pabrika?','[경험이 있으면] 네, [기간] 동안 [업무]를 했습니다. / [경험이 없으면] 아직 없습니다. 열심히 배우겠습니다.','If true: Yes, I did [work] for [duration]. Otherwise: Not yet. I will work hard to learn.','Kung totoo: Oo, ginawa ko ang [trabaho] sa loob ng [tagal]. Kung wala: Wala pa. Magsisikap akong matuto.'],
 ['Tools','이것은 무엇입니까?','What is this tool?','Ano ang kasangkapang ito?','이것은 망치입니다. 못을 박을 때 사용합니다.','This is a hammer. It is used to drive nails.','Ito ay martilyo. Ginagamit ito sa pagpukpok ng pako.','hammer'],
 ['Tools','이것은 무엇입니까?','What is this tool?','Ano ang kasangkapang ito?','이것은 드라이버입니다. 나사를 조이거나 풀 때 사용합니다.','This is a screwdriver. It is used to tighten or loosen screws.','Ito ay distornilyador. Ginagamit ito sa paghigpit o pagluwag ng turnilyo.','screwdriver'],
 ['Tools','이것은 무엇입니까?','What is this tool?','Ano ang kasangkapang ito?','이것은 스패너입니다. 볼트와 너트를 조이거나 풀 때 사용합니다.','This is a spanner. It is used to tighten or loosen bolts and nuts.','Ito ay liyabe. Ginagamit ito sa paghigpit o pagluwag ng bolt at nut.','wrench'],
 ['Tools','이것은 무엇입니까?','What is this tool?','Ano ang kasangkapang ito?','이것은 펜치입니다. 물건을 잡거나 철사를 구부릴 때 사용합니다.','These are pliers. They are used to grip objects or bend wire.','Ito ay plais. Ginagamit ito sa paghawak ng bagay o pagbaluktot ng alambre.','pliers'],
 ['Tools','줄자는 언제 사용합니까?','When do you use a tape measure?','Kailan ginagamit ang metro?','길이를 잴 때 사용합니다.','It is used to measure length.','Ginagamit ito sa pagsukat ng haba.'],
 ['Instructions','오른손을 들어 보세요.','Raise your right hand.','Itaas ang iyong kanang kamay.','[오른손을 듭니다.]','Perform the action: raise your right hand.','Gawin ang utos: itaas ang iyong kanang kamay.'],
 ['Instructions','왼쪽으로 돌아 보세요.','Turn to your left.','Lumiko pakaliwa.','[왼쪽으로 돕니다.]','Perform the action: turn to your left.','Gawin ang utos: lumiko pakaliwa.'],
 ['Instructions','지시를 이해하지 못하면 어떻게 하겠습니까?','What will you do if you do not understand an instruction?','Ano ang gagawin mo kung hindi mo naintindihan ang utos?','죄송합니다. 다시 설명해 주세요.','I am sorry. Please explain again.','Paumanhin. Pakipaliwanag muli.'],
 ['Safety','작업 전에 무엇을 확인해야 합니까?','What should you check before starting work?','Ano ang dapat suriin bago magsimula sa trabaho?','작업 지시와 기계 상태, 안전 장비를 확인해야 합니다.','Check work instructions, machine condition, and required protective equipment.','Suriin ang mga tagubilin, kondisyon ng makina, at kinakailangang protective equipment.'],
 ['Safety','기계가 고장 나면 어떻게 하겠습니까?','What will you do if a machine breaks down?','Ano ang gagawin mo kapag nasira ang makina?','작업을 멈추고 관리자에게 보고하겠습니다.','I will stop working and report it to the supervisor.','Hihinto ako sa trabaho at iuulat ito sa supervisor.'],
 ['Safety','왜 안전모를 써야 합니까?','Why should you wear a safety helmet?','Bakit kailangang magsuot ng safety helmet?','머리를 보호하기 위해서입니다.','To protect the head.','Upang maprotektahan ang ulo.'],
 ['Work habits','동료와 의견이 다르면 어떻게 하겠습니까?','What will you do if you disagree with a coworker?','Ano ang gagawin mo kung hindi kayo magkasundo ng katrabaho?','차분하게 이야기하고 필요하면 관리자에게 도움을 요청하겠습니다.','I will discuss it calmly and ask the supervisor for help if needed.','Kakausapin ko siya nang mahinahon at hihingi ng tulong sa supervisor kung kailangan.']
];
export function shuffledQuestions(){const list=[...questions];for(let i=list.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[list[i],list[j]]=[list[j],list[i]];}return list;}
if(typeof document!=='undefined'){
 let list=shuffledQuestions(),index=0,language='en';const $=s=>document.querySelector(s);
 const drawings={hammer:'<path d="M90 52L142 80L122 115L70 88Z" fill="#8195a8"/><path d="M105 104L58 191" stroke="#c98953" stroke-width="22"/>',screwdriver:'<path d="M118 36L111 46L112 137" stroke="#8398ab" stroke-width="10"/><rect x="97" y="125" width="31" height="76" rx="12" fill="#d97f51"/>',wrench:'<path d="M109 90L71 189" stroke="#879caf" stroke-width="21"/><path d="M103 93Q65 58 107 27L99 58L123 68L146 44Q153 96 103 93Z" fill="#879caf"/>',pliers:'<path d="M80 31L90 91L129 171M137 31L126 91L83 171" stroke="#879caf" stroke-width="15" fill="none"/><circle cx="109" cy="93" r="14" fill="#61788d"/><path d="M83 148L69 187M130 148L147 187" stroke="#ce7957" stroke-width="18"/>'};
 function render(){const q=list[index];$('#interview-progress').textContent=`${index+1} / ${list.length} · ${q[0]}`;$('#korean-question').textContent=q[1];$('#translation').textContent=q[language==='en'?2:3];$('#model-korean').textContent=q[4];$('#model-translation').textContent=q[language==='en'?5:6];$('#model').hidden=true;$('#show-answer').textContent=language==='en'?'Show sample response':'Ipakita ang halimbawang sagot';$('#tool-picture').innerHTML=q[7]?`<svg viewBox="0 0 220 220" role="img" aria-label="Manufacturing tool to identify">${drawings[q[7]]}</svg>`:'';$('#next-question').textContent=index===list.length-1?'New practice set':'Next question';}
 $('#language').addEventListener('change',event=>{language=event.target.value;render();});$('#show-answer').addEventListener('click',()=>{$('#model').hidden=false;});$('#next-question').addEventListener('click',()=>{if(++index===list.length){list=shuffledQuestions();index=0;}render();$('#korean-question').focus();});render();
}
