import {recordings} from './interview-audio.mjs';
export const questions=[
 ['Introduction','자기소개를 해 보세요.','Please introduce yourself.','Ipakilala ang iyong sarili.','안녕하세요. 저는 [이름]입니다. 필리핀에서 왔습니다. 제조업에서 성실하게 일하고 싶습니다. 감사합니다.','Hello. I am [name], from the Philippines. I would like to work diligently in manufacturing. Thank you.','Magandang araw. Ako si [pangalan], mula sa Pilipinas. Nais kong magtrabaho nang masipag sa manufacturing. Salamat.'],
 ['Introduction','왜 한국에서 일하고 싶습니까?','Why do you want to work in Korea?','Bakit mo gustong magtrabaho sa Korea?','한국에서 제조업 기술을 배우고 가족을 돕고 싶습니다.','I want to learn manufacturing skills in Korea and support my family.','Gusto kong matuto ng mga kasanayan sa manufacturing sa Korea at makatulong sa pamilya ko.'],
 ['Experience','공장에서 일한 경험이 있습니까?','Have you worked in a factory?','May karanasan ka bang magtrabaho sa pabrika?','[경험이 있으면] 네, [기간] 동안 [업무]를 했습니다. / [경험이 없으면] 아직 없습니다. 열심히 배우겠습니다.','If true: Yes, I did [work] for [duration]. Otherwise: Not yet. I will work hard to learn.','Kung totoo: Oo, ginawa ko ang [trabaho] sa loob ng [tagal]. Kung wala: Wala pa. Magsisikap akong matuto.'],
 ['Tools','이것은 무엇입니까?','What is this tool?','Ano ang kasangkapang ito?','이것은 망치입니다. 못을 박을 때 사용합니다.','This is a hammer. It is used to drive nails.','Ito ay martilyo. Ginagamit ito sa pagpukpok ng pako.','hammer'],
 ['Tools','이것은 무엇입니까?','What is this tool?','Ano ang kasangkapang ito?','이것은 드라이버입니다. 나사를 조이거나 풀 때 사용합니다.','This is a screwdriver. It is used to tighten or loosen screws.','Ito ay distornilyador. Ginagamit ito sa paghigpit o pagluwag ng turnilyo.','screwdriver'],
 ['Tools','이것은 무엇입니까?','What is this tool?','Ano ang kasangkapang ito?','이것은 스패너입니다. 볼트와 너트를 조이거나 풀 때 사용합니다.','This is a spanner. It is used to tighten or loosen bolts and nuts.','Ito ay liyabe. Ginagamit ito sa paghigpit o pagluwag ng bolt at nut.','wrench'],
 ['Tools','이것은 무엇입니까?','What is this tool?','Ano ang kasangkapang ito?','이것은 펜치입니다. 물건을 잡거나 철사를 구부릴 때 사용합니다.','These are pincers (combination pliers). They are used to grip objects or bend wire.','Ito ay plais. Ginagamit ito sa paghawak ng bagay o pagbaluktot ng alambre.','pliers'],
 ['Tools','줄자는 언제 사용합니까?','When do you use a tape measure?','Kailan ginagamit ang metro?','길이를 잴 때 사용합니다.','It is used to measure length.','Ginagamit ito sa pagsukat ng haba.'],
 ['Instructions','오른손을 들어 보세요.','Raise your right hand.','Itaas ang iyong kanang kamay.','[오른손을 듭니다.]','Perform the action: raise your right hand.','Gawin ang utos: itaas ang iyong kanang kamay.'],
 ['Instructions','왼쪽으로 돌아 보세요.','Turn to your left.','Lumiko pakaliwa.','[왼쪽으로 돕니다.]','Perform the action: turn to your left.','Gawin ang utos: lumiko pakaliwa.'],
 ['Instructions','지시를 이해하지 못하면 어떻게 하겠습니까?','What will you do if you do not understand an instruction?','Ano ang gagawin mo kung hindi mo naintindihan ang utos?','죄송합니다. 다시 설명해 주세요.','I am sorry. Please explain again.','Paumanhin. Pakipaliwanag muli.'],
 ['Safety','작업 전에 무엇을 확인해야 합니까?','What should you check before starting work?','Ano ang dapat suriin bago magsimula sa trabaho?','작업 지시와 기계 상태, 안전 장비를 확인해야 합니다.','Check work instructions, machine condition, and required protective equipment.','Suriin ang mga tagubilin, kondisyon ng makina, at kinakailangang protective equipment.'],
 ['Safety','기계가 고장 나면 어떻게 하겠습니까?','What will you do if a machine breaks down?','Ano ang gagawin mo kapag nasira ang makina?','작업을 멈추고 관리자에게 보고하겠습니다.','I will stop working and report it to the supervisor.','Hihinto ako sa trabaho at iuulat ito sa supervisor.'],
 ['Safety','왜 안전모를 써야 합니까?','Why should you wear a safety helmet?','Bakit kailangang magsuot ng safety helmet?','머리를 보호하기 위해서입니다.','To protect the head.','Upang maprotektahan ang ulo.'],
 ['Work habits','동료와 의견이 다르면 어떻게 하겠습니까?','What will you do if you disagree with a coworker?','Ano ang gagawin mo kung hindi kayo magkasundo ng katrabaho?','차분하게 이야기하고 필요하면 관리자에게 도움을 요청하겠습니다.','I will discuss it calmly and ask the supervisor for help if needed.','Kakausapin ko siya nang mahinahon at hihingi ng tulong sa supervisor kung kailangan.']
];
questions.push(
 ['Introduction','이름이 무엇입니까?','What is your name?','Ano ang pangalan mo?','제 이름은 [이름]입니다.','My name is [name].','Ang pangalan ko ay [pangalan].'],
 ['Introduction','어느 나라에서 왔습니까?','Which country are you from?','Saang bansa ka galing?','필리핀에서 왔습니다.','I am from the Philippines.','Galing ako sa Pilipinas.'],
 ['Introduction','한국어를 얼마나 공부했습니까?','How long have you studied Korean?','Gaano ka na katagal nag-aaral ng Korean?','[기간] 동안 한국어를 공부했습니다.','I have studied Korean for [duration].','Nag-aral ako ng Korean sa loob ng [tagal].'],
 ['Experience','어떤 일을 할 수 있습니까?','What work can you do?','Anong trabaho ang kaya mong gawin?','[실제로 할 수 있는 업무]를 할 수 있습니다.','I can do [work you can actually perform].','Kaya kong gawin ang [trabahong talagang kaya mong gawin].'],
 ['Tools','드릴은 언제 사용합니까?','When do you use a drill?','Kailan ginagamit ang barena?','구멍을 뚫을 때 사용합니다.','It is used to make holes.','Ginagamit ito sa pagbubutas.','drill'],
 ['Tools','육각 렌치는 언제 사용합니까?','When do you use an Allen key?','Kailan ginagamit ang Allen key?','육각 구멍이 있는 나사를 조이거나 풀 때 사용합니다.','To tighten or loosen screws with a hexagonal socket.','Sa paghigpit o pagluwag ng turnilyong may heksagonal na butas.','allen-key'],
 ['Tools','작업이 끝나면 공구를 어디에 놓습니까?','Where do you put tools after work?','Saan inilalagay ang mga kasangkapan matapos magtrabaho?','정해진 보관 장소에 놓습니다.','In their designated storage place.','Sa nakatalagang lagayan.'],
 ['Instructions','두 손을 앞으로 뻗어 보세요.','Stretch both hands forward.','Iunat ang dalawang kamay sa harap.','[두 손을 앞으로 뻗습니다.]','Perform the action: stretch both hands forward.','Gawin ang utos: iunat ang dalawang kamay sa harap.'],
 ['Instructions','앉았다가 일어나 보세요.','Sit down, then stand up.','Umupo, pagkatapos ay tumayo.','[앉은 다음 일어납니다.]','Perform the action: sit down, then stand up.','Gawin ang utos: umupo, pagkatapos ay tumayo.'],
 ['Instructions','망치를 가리켜 보세요.','Point to the hammer.','Ituro ang martilyo.','[망치를 가리킵니다.]','Point to a hammer in your practice tool set.','Ituro ang martilyo sa iyong mga kasangkapang pangpraktis.'],
 ['Safety','제품에 불량이 있으면 어떻게 하겠습니까?','What will you do if a product has a defect?','Ano ang gagawin mo kung may depekto ang produkto?','정해진 절차에 따라 분리하고 관리자에게 보고하겠습니다.','I will separate it according to procedure and report it to the supervisor.','Ihihiwalay ko ito ayon sa tamang proseso at iuulat sa supervisor.'],
 ['Safety','바닥에 기름이 있으면 어떻게 하겠습니까?','What will you do if there is oil on the floor?','Ano ang gagawin mo kung may langis sa sahig?','사람들이 접근하지 않도록 알리고 관리자에게 보고하겠습니다.','I will warn people to stay clear and report it to the supervisor.','Babalaan ko ang mga tao na umiwas at iuulat ito sa supervisor.'],
 ['Safety','무거운 물건을 혼자 들기 어려우면 어떻게 하겠습니까?','What will you do if an item is too heavy to lift alone?','Ano ang gagawin mo kung masyadong mabigat ang bagay para buhatin mag-isa?','도움을 요청하고 정해진 운반 장비를 사용하겠습니다.','I will ask for help and use the designated handling equipment.','Hihingi ako ng tulong at gagamit ng nakatalagang kagamitan sa pagbubuhat.'],
 ['Work habits','작업에 실수가 있으면 어떻게 하겠습니까?','What will you do if you make a mistake at work?','Ano ang gagawin mo kung nagkamali ka sa trabaho?','숨기지 않고 바로 관리자에게 보고하겠습니다.','I will report it promptly to the supervisor rather than hide it.','Iuulat ko agad ito sa supervisor at hindi itatago.'],
 ['Work habits','새로운 작업을 배우면 어떻게 하겠습니까?','How will you learn a new task?','Paano ka matututo ng bagong gawain?','설명을 잘 듣고 모르는 것은 질문하겠습니다.','I will listen carefully and ask about anything I do not understand.','Makikinig ako nang mabuti at magtatanong tungkol sa hindi ko naiintindihan.']
);
questions.push(
 ['Basic conversation','오늘은 무슨 요일입니까?','What day of the week is it today?','Anong araw ngayon?','예: 오늘은 월요일입니다. 실제 요일에 맞게 대답하세요.','Example: Today is Monday. Answer with the actual day.','Halimbawa: Lunes ngayon. Isagot ang tamang araw.'],
 ['Basic conversation','지금 몇 시입니까?','What time is it now?','Anong oras na ngayon?','예: 지금은 아홉 시 삼십 분입니다. 실제 시간에 맞게 대답하세요.','Example: It is 9:30 now. Answer with the actual time.','Halimbawa: Alas-nuwebe y medya na. Isagot ang tamang oras.'],
 ['Basic conversation','오늘은 몇 월 며칠입니까?','What is today’s date?','Ano ang petsa ngayon?','예: 오늘은 십월 오일입니다. 실제 날짜에 맞게 대답하세요.','Example: Today is October 5. Answer with the actual date.','Halimbawa: Oktubre 5 ngayon. Isagot ang tamang petsa.'],
 ['Basic conversation','내일은 무슨 요일입니까?','What day of the week is tomorrow?','Anong araw bukas?','예: 내일은 화요일입니다. 실제 요일에 맞게 대답하세요.','Example: Tomorrow is Tuesday. Use the actual day.','Halimbawa: Martes bukas. Gamitin ang tamang araw.'],
 ['Basic conversation','어제는 무슨 요일이었습니까?','What day of the week was yesterday?','Anong araw kahapon?','예: 어제는 일요일이었습니다. 실제 요일에 맞게 대답하세요.','Example: Yesterday was Sunday. Use the actual day.','Halimbawa: Linggo kahapon. Gamitin ang tamang araw.'],
 ['Basic conversation','몇 시에 일어납니까?','What time do you get up?','Anong oras ka bumabangon?','예: 오전 여섯 시에 일어납니다.','Example: I get up at six in the morning.','Halimbawa: Bumabangon ako nang alas-sais ng umaga.'],
 ['Basic conversation','몇 시에 잡니까?','What time do you go to sleep?','Anong oras ka natutulog?','예: 밤 열 시에 잡니다.','Example: I go to sleep at ten at night.','Halimbawa: Natutulog ako nang alas-diyes ng gabi.'],
 ['Basic conversation','오늘 날씨가 어떻습니까?','How is the weather today?','Kumusta ang panahon ngayon?','예: 오늘은 맑습니다. 실제 날씨에 맞게 대답하세요.','Example: It is clear today. Answer for the actual weather.','Halimbawa: Maaliwalas ngayon. Isagot ang aktuwal na panahon.'],
 ['Basic conversation','생일이 언제입니까?','When is your birthday?','Kailan ang iyong kaarawan?','제 생일은 [월]월 [일]일입니다.','My birthday is [month] [day].','Ang kaarawan ko ay [buwan] [araw].'],
 ['Basic conversation','지금 어디에 살고 있습니까?','Where do you live now?','Saan ka nakatira ngayon?','지금 [도시]에 살고 있습니다.','I currently live in [city].','Nakatira ako ngayon sa [lungsod].'],
 ['Basic conversation','오늘 아침에 무엇을 먹었습니까?','What did you eat this morning?','Ano ang kinain mo ngayong umaga?','예: 오늘 아침에 밥과 달걀을 먹었습니다.','Example: I ate rice and eggs this morning.','Halimbawa: Kumain ako ng kanin at itlog ngayong umaga.'],
 ['Basic conversation','학교에 어떻게 옵니까?','How do you get to school?','Paano ka pumupunta sa paaralan?','예: 버스를 타고 옵니다.','Example: I come by bus.','Halimbawa: Sumasakay ako ng bus.']
);
export function shuffledQuestions(){const list=[...questions];for(let i=list.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[list[i],list[j]]=[list[j],list[i]];}return list;}
if(typeof document!=='undefined'){
 let list=shuffledQuestions(),index=0,language='en';const $=s=>document.querySelector(s);
 const toolImages=Object.fromEntries(['hammer','screwdriver','wrench','pliers','drill','allen-key'].map(key=>[key,`media/eps-topik/interview-tools/${key}.png`]));
 function render(){const q=list[index];$('#interview-progress').textContent=`${index+1} / ${list.length} · ${q[0]}`;$('#korean-question').textContent=q[1];$('#translation').textContent=q[language==='en'?2:3];$('#model-korean').textContent=q[4];$('#model-translation').textContent=q[language==='en'?5:6];$('#model').hidden=true;$('#show-answer').textContent=language==='en'?'Show sample response':'Ipakita ang halimbawang sagot';$('#tool-picture').innerHTML=q[7]?`<img src="${toolImages[q[7]]}" alt="EPS textbook manufacturing tool for this question">`:'';$('#next-question').textContent=index===list.length-1?'New practice set':'Next question';}
 const audio=new Audio();audio.preload='none';let playback=0;
 function stopAudio(){playback++;audio.pause();audio.removeAttribute('src');audio.load();$('#audio-status').textContent='';}
 audio.addEventListener('ended',()=>{$('#audio-status').textContent='';});
 audio.addEventListener('error',()=>{if(audio.getAttribute('src'))$('#audio-status').textContent='Could not load the recording. Check your connection and try again.';});
 $('#listen-question').addEventListener('click',async()=>{stopAudio();const current=playback;audio.src=recordings[list[index][1]];$('#audio-status').textContent='Loading Korean recording…';try{await audio.play();if(current===playback)$('#audio-status').textContent='Playing Korean question…';}catch{if(current===playback)$('#audio-status').textContent='Unable to play audio. Please tap Listen again.';}});
 $('#stop-audio').addEventListener('click',stopAudio);window.addEventListener('pagehide',stopAudio);
 $('#language').addEventListener('change',event=>{stopAudio();language=event.target.value;render();});$('#show-answer').addEventListener('click',()=>{$('#model').hidden=false;});$('#next-question').addEventListener('click',()=>{stopAudio();if(++index===list.length){list=shuffledQuestions();index=0;}render();$('#korean-question').focus();});render();
}
