import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {questions,shuffledQuestions} from '../js/interview.mjs';import {protectedPath} from '../access/worker.mjs';
import {recordings} from '../js/interview-audio.mjs';
test('every Korean interview question has a local MP3 recording',()=>{for(const q of questions){const file=recordings[q[1]];assert.match(file,/^media\/interview\/[a-f0-9]{16}\.mp3$/);const data=fs.readFileSync(new URL('../'+file,import.meta.url));assert.ok(data.length>2000);assert.ok(data.subarray(0,3).toString()==='ID3'||data[0]===255);}const script=fs.readFileSync(new URL('../js/interview.mjs',import.meta.url),'utf8');assert.ok(!script.includes('speechSynthesis'));});
test('expanded practice has 90 bilingual questions and accessible listening controls',()=>{assert.equal(questions.length,90);assert.equal(questions.filter(q=>q[0]==='Basic conversation').length,12);const html=fs.readFileSync(new URL('../skills.html',import.meta.url),'utf8');assert.ok(html.includes('id="listen-question"'));assert.ok(html.includes('id="stop-audio"'));assert.ok(html.includes('id="audio-status" role="status"'));});
test('interview practice keeps Korean, English and Tagalog prompts and responses together',()=>{const shuffled=shuffledQuestions();assert.equal(shuffled.length,questions.length);assert.equal(new Set(shuffled).size,questions.length);for(const q of questions){assert.ok(q.slice(0,7).every(v=>typeof v==='string'&&v.length));assert.ok(shuffled.includes(q));}assert.equal(questions.filter(q=>q[7]).length,24);assert.ok(protectedPath('/skills.html'));const html=fs.readFileSync(new URL('../skills.html',import.meta.url),'utf8');assert.ok(html.includes('PLLEGIrzXovgsYYywpR0hUMZJ6xrlfUkN9'));assert.ok(html.includes('PLLEGIrzXovgvXnQ3TdDZ4l2Al87tTJbVw'));});

test('textbook tool images and both languages of manufacturing guides are available',()=>{for(const q of questions.filter(q=>q[7])){assert.ok(fs.readFileSync(new URL('../media/eps-topik/interview-tools/'+q[7]+'.png',import.meta.url)).length>1000);}const html=fs.readFileSync(new URL('../skills.html',import.meta.url),'utf8');for(const id of ['6WvnK2a_CEU','NCzvZMXRs8g','L3cp0C92vBQ','nwETwGnmelc','V7b7LLXP414','nYB4jF_zaCQ'])assert.ok(html.includes(id));assert.ok(html.includes('printed pages 87, 90 and 97'));});

test('2026 memo practice is manufacturing-only and covers all safety stages',()=>{assert.equal(shuffledQuestions('new-tools').length,18);for(const [stage,count] of [['Before work',6],['During work',14],['After work',5],['Abnormal situations',5]])assert.equal(shuffledQuestions(stage).length,count);assert.equal(shuffledQuestions('general').length,42);assert.ok(questions.filter(q=>q[8]).every(q=>q[8].includes('HRDK memo')));});
